### ISSUE TITLE
Cannot get line numbering working using editor_props

### ISSUE THREAD

**Issue by dividor** [bouzidanas/streamlit-code-editor#11]
An amazing piece of work, thanks!

I would like to activate line number in my editor. Following [the documentation](https://code-editor-documentation.streamlit.app/Advanced_customization#customizing-the-ace-editor) it suggests I should be able to do this by passing in `editor_props` dictionary to code_editor. However, when I try ...

`response_dict = code_editor(code, buttons=buttons, editor_props={"showLineNumbers":True})`

It doesn't add line numbers.

Is there something I'm doing wrong please?

**Comment by bouzidanas** [comment]
Hi,

Its under options : https://github.com/ajaxorg/ace/wiki/Configuring-Ace#editor-options

So just add:
```python
options={"showLineNumbers": True}
```
to `code_editor` function.

Best of luck with your project!

**Comment by dividor** [comment]
Perfect, that did the trick, thanks!!
