### ISSUE TITLE
Auto suggestion is not working so well

### ISSUE THREAD

**Issue by xihajun** [bouzidanas/streamlit-code-editor#16]
<img width="827" alt="image" src="https://github.com/bouzidanas/streamlit-code-editor/assets/25631641/26b9bf01-a133-4841-a7b3-1c8e5960c59d">

Thanks a lot for this awesome project, I wonder if it is possible to disable this auto suggestion?

**Comment by bouzidanas** [comment]
Yes. Do you want to remove snippet suggestions, all suggestions, or that single snippet suggestions?

**Comment by xihajun** [comment]
Like if we can disable all suggestions would be cool :)

**Comment by bouzidanas** [comment]
To dissable autocomplete and snippets suggestions, just set the following in `code_editor` function:
```py
response_dict = code_editor(your_code_string, props={ "enableBasicAutocompletion": False, "enableLiveAutocompletion": False, "enableSnippets": False})
```

**Comment by xihajun** [comment]
Thanks a lot!
